---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: longhorn-ui-auth
  namespace: longhorn-system
spec:
  encryptedData:
    auth: AgBOvWpZzEeL5xcD+HrjL3lKYMKUKWPL3EBx+31dXAEIKw3ilLDIFHH0RIGEt9Da+wh0k8BUpGjEI3X79I0TetNOu/1anJV54/XrNgjCOKodgBcDcEFQmSZzQRh7Ss1eXPrOr5W2tN7jWGdl9k5vc76RghWsBjjtPS68QvNl/VA4cSj7OOFwsQCh/WAZXpa9iY/xbggB+xF5lkuPW+TLgpDmAeL8bi/4jxGIR3TUtwyERY34QvGUSYjqcLIZKijt63Xp6/gdYI+g6HRdYuoWnHAX09ebPlgqs8U+ISWI8EN4KezlIXGbnnqUwIFwHkIsbWfYQo8dAIwY6Lmh9u/44Z2Ykv6OnGJWRIXtWqPPCnK0eaaG3Sfy+rqP7xE7j4LgvhebWU2jL4OnWt+GrjR/5OwG6GfxiCd9C9vovtYuc2Twbgp7HPBY6hAM2Lyr53NSydXM8Wol+WlTBwWp9D/UIicRHuwV9v6Hd9P8Cwg9VhHMZfsIP1nsvikM4nGsJvQtFOTYaLB+aEaYYVcFkKrHzXug+J6tHd/+P015U1Ux4o7MC7jJEt7zsQccg6WlEPElD70sa3aSjtw9JwCxPsw4vhPp2x/c8VNMsxbR73kh9tA4lgeYsjeUMjp3v2Njbpggsw9M/Vp+p6XNdHEeDlaEPSGtZI0cZSYgvDXOLFYrLqKGsI39uevCn5+F4IyHikYs8f5wtOsumr0oBKUBxutnnuPPajk/pdDu39e0SzEdN2tqjmRVOMnMxku4TV8WYcw=
  template:
    metadata:
      name: longhorn-ui-auth
      namespace: longhorn-system
